# Generated by Django 2.0.13 on 2019-10-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191022_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='image3',
            new_name='image2',
        ),
    ]
