# Generated by Django 2.0.13 on 2019-10-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191022_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images//'),
        ),
    ]
