# Generated by Django 2.0.13 on 2019-11-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191029_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='images',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
