# Generated by Django 2.0.13 on 2019-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191103_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
